# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SuperSnake < Formula
  desc "Play Snake Xenzia in your terminal"
  homepage "https://github.com/the-Jinxist/super_snake"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/the-Jinxist/super_snake/releases/download/v1.3.0/super_snake_Darwin_x86_64.tar.gz"
      sha256 "dcc37991be4c65581151f3d543a01303e659e12cf1d9d24f64946adb4d575f6c"

      def install
        bin.install "super_snake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/the-Jinxist/super_snake/releases/download/v1.3.0/super_snake_Darwin_arm64.tar.gz"
      sha256 "25e7c75556e4bb19b80ca410c1979b47173d337291e276a6f1bbf76b9147ba8e"

      def install
        bin.install "super_snake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-Jinxist/super_snake/releases/download/v1.3.0/super_snake_Linux_x86_64.tar.gz"
      sha256 "c2efb0eeb0437d7d38ff5bc43c0859fce6dc2bee29fa22b6e8e3a47d1b6dca43"
      def install
        bin.install "super_snake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-Jinxist/super_snake/releases/download/v1.3.0/super_snake_Linux_arm64.tar.gz"
      sha256 "d010078fb9ee6e445281a31a83e10aa955d4fda38f0699dfd519d9acb655f937"
      def install
        bin.install "super_snake"
      end
    end
  end

  def post_install
    super_snake --help
  end
end
