# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SuperSnake < Formula
  desc "Play Snake Xenzia in your terminal"
  homepage "https://github.com/the-Jinxist/golang_snake_game"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/the-Jinxist/golang_snake_game/releases/download/v1.0.1/golang_snake_game_Darwin_x86_64.tar.gz"
      sha256 "a8e283442d4639b70cb052fe03df8c460fc82747247e7534a44b33a07caccaf8"

      def install
        bin.install "golang_snake_game"
      end
    end
    on_arm do
      url "https://github.com/the-Jinxist/golang_snake_game/releases/download/v1.0.1/golang_snake_game_Darwin_arm64.tar.gz"
      sha256 "a77e0a38d076488a023af15ab5eaaa8c4d7ef55f4992e075421df2f6b51c2cad"

      def install
        bin.install "golang_snake_game"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/golang_snake_game/releases/download/v1.0.1/golang_snake_game_Linux_x86_64.tar.gz"
        sha256 "dab17b83acb1a9dbf89c29587b84f1ec1a06d21002ceb68ea461882957b77902"

        def install
          bin.install "golang_snake_game"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/the-Jinxist/golang_snake_game/releases/download/v1.0.1/golang_snake_game_Linux_arm64.tar.gz"
        sha256 "74c2435f65f14a0ed58e0993f04525ad08922d0e07557a9ac6d74cfef9a6b5dc"

        def install
          bin.install "golang_snake_game"
        end
      end
    end
  end

  def post_install
    golang_snake_game --help
  end
end
