# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SuperSnake < Formula
  desc "Play Snake Xenzia in your terminal"
  homepage "https://github.com/the-Jinxist/super_snake"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/the-Jinxist/super_snake/releases/download/v1.1.0/super_snake_Darwin_x86_64.tar.gz"
      sha256 "ff29a682406fca3d45df1442a59d3eb245289535d9ffb050a37d73d7f5e4ac89"

      def install
        bin.install "super_snake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/the-Jinxist/super_snake/releases/download/v1.1.0/super_snake_Darwin_arm64.tar.gz"
      sha256 "25bccdfb202613ba0df744f74ab9c834e40b121652a72d17408a6e8816ed1821"

      def install
        bin.install "super_snake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-Jinxist/super_snake/releases/download/v1.1.0/super_snake_Linux_x86_64.tar.gz"
      sha256 "6711755323aaceb1647e5c6e076f1db1cf9f8e9e2108f3c2550603f803ce9fad"
      def install
        bin.install "super_snake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/the-Jinxist/super_snake/releases/download/v1.1.0/super_snake_Linux_arm64.tar.gz"
      sha256 "d1aa43c8db621bf48bf75073ffa647353b4a63f3be54b088ddc7398baaef1420"
      def install
        bin.install "super_snake"
      end
    end
  end

  def post_install
    super_snake --help
  end
end
